version: '3'
services:
  api:
    environment:
      PYTHONUNBUFFERED: 1
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
