version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: 1
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: password
      AUTH_KEY: testing_secret
    stdin_open: true
    tty: true
  db:
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_db:
