name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker-compose build
    - name: Run docker container
      run: docker-compose up -d
    - name: Run tests
      run: docker exec -it api pytest
